---
- name: Configure neutron-network server
  hosts: neutron-network
  sudo: True
  gather_facts: True
  vars:
    component: neutron
    packages:
        - openstack-neutron
        - mlnx-dnsmasq
    services:
        - neutron-linuxbridge-agent
        - neutron-dhcp-agent
        - neutron-metadata-agent
        - neutron-l3-agent
        - opensmd
        - openibd
    config_files:
      - "{{ component }}.conf"
      - api-paste.ini
      - dhcp_agent.ini
      - l3_agent.ini
      - metadata_agent.ini

  tasks:

    - name: ensure iptables configuration is present
      template: 
        src: templates/etc/iptables.rules 
        dest: /etc/iptables.rules 
        owner: root 
        group: root 
        mode: 0644

    - name: load iptables rules
      shell: /sbin/iptables-restore < /etc/iptables.rules

    - name: ensure iptables configuration is loaded at boot
      template: 
        src: templates/etc/network/if-pre-up.d/iptablesload 
        dest: /etc/network/if-pre-up.d/iptablesload 
        owner: root 
        group: root 
        mode: 0755

    - name: ensure {{ component }}-network packages are installed
      yum: 
        name: "{{ item }}"
        state: latest 
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: update linuxbridge_conf.ini from template
      template: 
        src: templates/etc/neutron/plugins/linuxbridge/linuxbridge_conf.ini 
        dest: /etc/neutron/plugins/linuxbridge/linuxbridge_conf.ini 
        owner: neutron 
        group: neutron 
        mode: 0600

    - name: copy ipoibd and override /sbin/ipoibd
      get_url:
        url: 'http://www.mellanox.com/downloads/solutions/openstack/havana/ipoibd'
        dest: /sbin/ipoibd

    - name: copy linuxbridge patch
      get_url:
        url: 'http://www.mellanox.com/downloads/solutions/openstack/havana/patches/linuxbridge_neutron_agent.py.patch'
        dest: /tmp/linux_bridge_agent.py.patch

    - name: apply linuxbridge patch
      shell: 'patch -p1 < /tmp/linux_bridge_agent.py.patch chdir=/usr/lib/python2.6/site-packages/neutron/plugins/linuxbridge/agent'

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services

