---
- name: Install and configure mlnx neutron agent
  hosts: neutron-network:nova-compute
  sudo: True
  gather_facts: True
  vars:
    component: neutron
    subcomponent: mlnx
    download_repo: http://www.mellanox.com/downloads/solutions/openstack/havana/repo/mlnx-havana/mlnx-havana.repo
    packages:
      - eswitchd
      - mlnxvif
      - mlnx-dnsmasq
      - openstack-neutron-mellanox
    services:
      - openstack-nova-compute
      - eswitchd
      - neutron-plugin-mlnx-agent
    config_files:
      - api-paste.ini

  tasks:

    - name: enable net.ipv4.ip_forward in sysctl
      sysctl: 
        name: net.ipv4.ip_forward 
        value: "1"
        state: present

    - name: enable net.ipv4.conf.all.forwarding in sysctl
      sysctl: 
        name: net.ipv4.conf.all.forwarding 
        value: "1"
        state: present

    - name: disable net.ipv4.conf.all.rp_filter in sysctl
      sysctl: 
        name: net.ipv4.conf.all.rp_filter 
        value: "0"
        state: present

    - name: disable net.ipv4.conf.default.rp_filter in sysctl
      sysctl: 
        name: net.ipv4.conf.default.rp_filter 
        value: "0"
        state: present

    - name: ensure Mellanox repo is downloaded in /etc/yum.repos.d
      get_url:
        url: "{{ download_repo }}"
        dest: /etc/yum.repos.d/mlnx-havana.repo

    - name: ensure {{ component }}-{{ subcomponent }} packages are installed
      yum: 
        name: "{{ item }}"
        state: latest 
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services
      ignore_errors: yes

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: ensure mlnx plugins directory exists
      file:
        path: /etc/{{ component }}/plugins/mlnx
        owner: "{{ component }}"
        group: "{{ component }}"
        recurse: yes
        state: directory

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: update mlnx_conf.ini from template
      template: 
        src: templates/etc/neutron/plugins/mlnx/mlnx_conf.ini 
        dest: /etc/neutron/plugins/mlnx/mlnx_conf.ini 
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600

    - name: make sure symlink to mlnx_conf.ini exists
      file: 
        src: /etc/neutron/plugins/mlnx/mlnx_conf.ini 
        dest: /etc/neutron/plugin.ini 
        state: link

    - name: ensure {{ component }} logs have correct owner
      file:
        path: "/var/log/{{ component }}"
        recurse: yes
        state: directory
        group: "{{ component }}"
        owner: "{{ component }}"

    - name: ensure neutron mlnx services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services
      ignore_errors: yes

