---
- name: Install and configure mlnx neutron agent
  hosts: neutron-network:nova-compute
  sudo: True
  gather_facts: True
  vars:
    component: neutron
    subcomponent: mlnx
    download_url: http://www.mellanox.com/downloads/solutions/openstack/havana/debian/
    downloads:
      - eswitchd_0.6-1_amd64.deb
      - python-mlnxvif_0.6-1_all.deb
      - python-mlnx-dnsmasq_0.1-1_all.deb
    packages:
      - eswitchd
      - python-mlnxvif
      - python-mlnx-dnsmasq
      - neutron-plugin-mlnx-agent
    services:
      - eswitchd
      - neutron-plugin-mlnx-agent
    config_files:
      - api-paste.ini

  tasks:

    - name: enable net.ipv4.ip_forward in sysctl
      sysctl: 
        name: net.ipv4.ip_forward 
        value: "1"
        state: present

    - name: enable net.ipv4.conf.all.forwarding in sysctl
      sysctl: 
        name: net.ipv4.conf.all.forwarding 
        value: "1"
        state: present

    - name: disable net.ipv4.conf.all.rp_filter in sysctl
      sysctl: 
        name: net.ipv4.conf.all.rp_filter 
        value: "0"
        state: present

    - name: disable net.ipv4.conf.default.rp_filter in sysctl
      sysctl: 
        name: net.ipv4.conf.default.rp_filter 
        value: "0"
        state: present

    - name: ensure {{ downloads }} packages are downloaded in /tmp
      get_url:
        url: {{ download_url }}/{{ item }}
        dest: /tmp/{{ item }}
      with_items: downloads

    - name: ensure {{ downloads }} packages are installed
      command: dpkg --skip-same-version -i /tmp/{{ item }}
      register: dpkg_result
      changed_when: "dpkg_result.stdout.startswith('Selecting')"
      with_items: downloads

    - name: fix any dependencies, if needed
      command: apt-get install -f

    - name: ensure {{ component }}-{{ subcomponent }} packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: update mlnx_conf.ini from template
      template: 
        src: templates/etc/neutron/plugins/mlnx/mlnx_conf.ini 
        dest: /etc/neutron/plugins/mlnx/mlnx_conf.ini 
        owner: neutron 
        group: neutron 
        mode: 0600

    - name: make sure symlink to mlnx_conf.ini exists
      file: 
        src: /etc/neutron/plugins/mlnx/mlnx_conf.ini 
        dest: /etc/neutron/plugin.ini 
        state: link

    - name: ensure neutron mlnx services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services

