---
- name: Configure keystone server
  hosts: keystone
  sudo: True
  gather_facts: True
  vars:
    component: keystone
    packages:
      - "openstack-{{ component }}"
      - "python-{{ component }}client"
    services:
      - "openstack-{{ component }}"
    config_files:
      - "{{ component }}.conf"

  tasks:

    - name: ensure {{ component }} packages are installed
      yum: 
        name: "{{ item }}"
        state: latest 
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: ensure database is synced
      command: /usr/bin/{{ component }}-manage db_sync

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services

    # keystone seems to take a while...
    - name: wait for keystone to come back up
      wait_for: 
        host: "{{ keystone_endpoint_host }}" 
        port: 35357

    - name: create service tenant
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}" 
        tenant: service 
        tenant_description: "Service Tenant"

    - name: add keystone endpoint information
      keystone_service: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}" 
        region: "{{ openstack_region }}"
        name: keystone
        type: identity
        description: "Identity Service"
        public_url: "{{ keystone_public_url }}"
        internal_url: "{{ keystone_internal_url }}"
        admin_url: "{{ keystone_admin_url }}"

    - name: create admin tenant
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}" 
        tenant: admin
        tenant_description: "Admin Tenant"

    - name: create admin user
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}" 
        tenant: admin
        user: admin 
        password: "{{ admin_password }}"

    - name: create admin role and associate it with admin user
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}" 
        tenant: admin
        user: admin 
        role: admin
