---
- name: gather needed facts for template
  hosts: mysql:rabbitmq:keystone:glance:neutron-api:nova-controller

- name: Install nova compute on nodes
  hosts: nova-compute
  sudo: True
  gather_facts: True
  vars:
    component: nova-compute
    services:
      - "openstack-{{ component }}"
      - libvirtd 
      - messagebus
  tasks:

    - name: ensure /boot/vmlinuz is world-readable
      shell: chmod 0644 /boot/vmlinuz*

    - name: ensure {{ component }} packages are installed
      yum: 
        name: "{{ item }}"
        state: latest 
      with_items:
        - "{{ nova_compute_package }}"
      
    - name: ensure {{ component }} services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure nova.conf file is present
      template: 
        src: templates/etc/nova/nova.conf 
        dest: /etc/nova/nova.conf 
        owner: nova 
        group: nova 
        mode: 0600

    - name: update api-paste.ini from template
      template: 
        src: templates/etc/nova/api-paste.ini 
        dest: /etc/nova/api-paste.ini 
        owner: nova 
        group: nova 
        mode: 0600

    - name: ensure {{ component }} configs have correct owner
      file:
        path: "/etc/nova"
        recurse: yes
        state: directory
        group: nova
        owner: nova

    - name: ensure {{ component }} logs have correct owner
      file:
        path: "/var/log/nova"
        recurse: yes
        state: directory
        group: nova
        owner: nova

    - name: ensure {{ component }} has lock subsys creation
      file:
        path: "/var/lock/subsys/nova"
        recurse: yes
        state: directory
        group: nova
        owner: nova

    - name: ensure {{ component }} services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services
