---
- name: Configure nova-controller server
  hosts: nova-controller
  sudo: True
  gather_facts: True
  vars:
    component: nova
    packages:
      - "openstack-{{ component }}"
      - novnc
      - "python-{{ component }}client"
    services:
      - "openstack-{{ component }}-api"
      - "openstack-{{ component }}-cert"
      - "openstack-{{ component }}-conductor"
      - "openstack-{{ component }}-consoleauth"
      - "openstack-{{ component }}-scheduler"
      - "openstack-{{ component }}-novncproxy"
    config_files:
      - "{{ component }}.conf"
      - api-paste.ini

  tasks:

    - name: ensure {{ component }}-controller packages are installed
      yum: 
        name: "{{ item }}"
        state: latest 
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: ensure database is synced
      command: /usr/bin/{{ component }}-manage db sync

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services

