---
- name: Configure glance server
  hosts: glance
  sudo: True
  gather_facts: True
  vars:
    component: glance 
    packages:
      - "openstack-{{ component }}"
    services:
      - "openstack-{{ component }}-api"
      - "openstack-{{ component }}-registry"
    config_files:
      - "{{ component }}-api.conf"
      - "{{ component }}-api-paste.ini"
      - "{{ component }}-registry.conf"
      - "{{ component }}-registry-paste.ini"

  tasks:

    - name: ensure {{ component }} packages are installed
      yum: 
        name: "{{ item }}"
        state: latest 
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: ensure database is synced
      command: /usr/bin/{{ component }}-manage db_sync

    - name: ensure {{ component }} logs have correct owner
      file:
        path: "/var/log/{{ component }}"
        recurse: yes
        state: directory
        group: "{{ component }}"
        owner: "{{ component }}"

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services

