---
- name: setup steps that are not specific to a particular role or project
  hosts: all
  sudo: True
  gather_facts: True
  tasks:

    - name: stop Network Manager
      service: 
        name: NetworkManager
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: start network
      service: 
        name: network
        state: started
        enabled: yes
      ignore_errors: yes

    - name: ensure required base packages are present
      yum: 
        name: "{{ item }}" 
        state: latest 
      with_items:
        - ntp
        - mysql
        - MySQL-python

    - name: start ntpd
      service: 
        name: ntpd
        state: started
        enabled: yes

    - name: set clocks to public ntp server
      command: ntpdate {{ external_ntp_host }}
      ignore_errors: yes

    - name: save system clock to hardware
      command: hwclock --systohc

    - name: register RDO openstack repo
      yum:
          name: http://repos.fedorapeople.org/repos/openstack/openstack-havana/rdo-release-havana-6.noarch.rpm
          state: present

    - name: install openstack repo keys
      yum:
          name: http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
          state: present

    - name: install base openstack packages
      yum:
          name: "{{ item }}"
          state: present
      with_items:
          - openstack-utils
          - openstack-selinux

#    - name: upgrade current packages to latest version
#      yum: 
#        name: '*'
#        state: latest 
#      ignore_errors: yes

    - include: reboot.yaml

- include: virtualbox.yaml
  when: ansible_virtualization_type|defined and ansible_virtualization_type == "virtualbox"
